# Generated by Django 5.2.8 on 2025-12-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userlocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlocation',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='userlocation',
            old_name='longitude',
            new_name='lng',
        ),
    ]
