# Generated by Django 5.2.8 on 2025-12-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_latitude_userlocation_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlocation',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='userlocation',
            old_name='lng',
            new_name='longitude',
        ),
    ]
